# Generated by Django 5.0.2 on 2024-04-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_receipe_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipe',
            name='view_count',
        ),
    ]
