# Generated by Django 5.0.2 on 2024-05-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_alter_reportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='date_of_generation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
